---
title: <div style='text-align: center;'>
  ماهیت واقعیت شخصی
</div>
logo: /assets/img/Logo.jpg
description: <div style='text-align: center;'>
کتابی از سِت/جین رابرتز/رابرت باتز
</div>
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
---

<style type="text/css">

h1.title {
  font-size: 38px;
  color: DarkRed;
  text-align: center;
}
